name:                ghc-pkg-find-module-multi
version:             0.1.0.0
github:              "carymrobbins/ghc-pkg-find-module-multi"
license:             BSD3
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2020 Cary Robbins"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Patched version of ghc-pkg which supports multiple modules for the find-module command.
category:            Compiler

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ghc-pkg-find-module-multi#readme>

dependencies:
- base >= 4.7 && < 5
- Cabal
- containers
- directory
- filepath
- ghc
- ghc-boot
- unix

executables:
  ghc-pkg-multi:
    main:                Main.hs
    source-dirs:
    - ./src
    - ./gen
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
